name: Pactum Mocha Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Pactum Mocha tests
      run: npm run test
    - run: npx testbeats@latest publish --slack ${{ secrets.SLACK_MVP_URL }} --junit reports/junit.xml --ci-info --chart-test-summary
      if: always()
      env:
        TEST_BEATS_API_KEY: ${{ secrets.TEST_BEATS_API_KEY }}
        TEST_BEATS_PROJECT: "testbeats/examples"